name: Build SO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip
        run: unzip jni_russian_menu.zip

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build
        run: |
          cd jni
          $ANDROID_NDK_HOME/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=Android.mk \
            NDK_APPLICATION_MK=Application.mk

      - name: Upload SO
        uses: actions/upload-artifact@v4
        with:
          name: luosu.so
          path: jni/libs/arm64-v8a/libluosu.so
